import { BlogPost, Category, ActivityLog, SeoConfig } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Customs Information',
    slug: '/customs-information',
    postCount: 5,
    createdDate: '2026-01-10',
  },
  {
    id: 'cat-2',
    name: 'Shipping Tips',
    slug: '/shipping-tips',
    postCount: 4,
    createdDate: '2026-01-15',
  },
  {
    id: 'cat-3',
    name: 'Express Air Freight',
    slug: '/express-air-freight',
    postCount: 2,
    createdDate: '2026-02-01',
  },
  {
    id: 'cat-4',
    name: 'Tracking Updates',
    slug: '/tracking-updates',
    postCount: 3,
    createdDate: '2026-02-20',
  },
  {
    id: 'cat-5',
    name: 'Logistics News',
    slug: '/logistics-news',
    postCount: 1,
    createdDate: '2026-03-05',
  },
];

export const INITIAL_BLOG_POSTS: BlogPost[] = [
  {
    id: 'post-1',
    title: 'How to Track International Shipments',
    slug: 'how-to-track-international-shipments',
    category: 'Customs Information',
    status: 'Published',
    publishDate: '2026-08-05',
    author: 'Admin',
    readTime: '6 minutes',
    shortSummary: 'A comprehensive guide to understanding global parcel movement, carrier handoffs, and real-time checkpoint updates.',
    bodyContent: '### Navigating Global Logistics\n\nInternational shipping involves multiple customs clearance stages, carrier transfers, and automated barcode scans. Tracking your parcel with ShipTrack provides real-time visibility across 150+ courier networks.\n\n#### Key Milestones to Watch\n- Export Customs Clearance\n- In-Transit International Flight\n- Import Customs Holding & Duties Assessment\n- Out for Final Mile Delivery',
    featuredImage: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80',
    targetKeywords: 'international tracking, customs clearance, package tracking, parcel status',
    seoTitle: 'How to Track International Shipments Guide | ShipTrack',
    seoDescription: 'Learn step-by-step how to track cross-border packages, navigate customs holds, and verify delivery dates.',
  },
  {
    id: 'post-2',
    title: 'Understanding Express Air Freight Delays',
    slug: 'understanding-express-air-freight-delays',
    category: 'Express Air Freight',
    status: 'Draft',
    publishDate: '2026-08-08',
    author: 'Admin',
    readTime: '4 minutes',
    shortSummary: 'Analyzing weather events, airport congestion, and flight capacity issues that impact priority delivery SLAs.',
    bodyContent: 'Air freight express services guarantee tight delivery windows, but severe weather or security checks can hold shipments at hub facilities.',
    featuredImage: 'https://images.unsplash.com/photo-1542296332-2e4473faf563?auto=format&fit=crop&w=800&q=80',
    targetKeywords: 'air freight, express shipment, delivery delay, flight cargo',
    seoTitle: 'Why Express Air Freight Delays Happen | ShipTrack Insights',
    seoDescription: 'Discover the top reasons behind air cargo holds and how automated notifications keep customers updated.',
  },
  {
    id: 'post-3',
    title: '5 Essential Packaging Tips for Fragile Goods',
    slug: '5-essential-packaging-tips-for-fragile-goods',
    category: 'Shipping Tips',
    status: 'Published',
    publishDate: '2026-07-28',
    author: 'Admin',
    readTime: '5 minutes',
    shortSummary: 'Avoid package damage with double-boxing techniques, cushioning ratios, and proper barcode label placement.',
    bodyContent: 'Protecting valuable shipments begins with selecting the right box strength and shock-absorption materials.',
    featuredImage: 'https://images.unsplash.com/photo-1566576721346-d4a3b4eaeb55?auto=format&fit=crop&w=800&q=80',
    targetKeywords: 'fragile packaging, shipping box tips, parcel protection',
    seoTitle: '5 Essential Packaging Tips for Fragile Shipments',
    seoDescription: 'Best practices for packing glassware, electronics, and delicate items for safe transit.',
  },
  {
    id: 'post-4',
    title: 'Decoding Customs Tariff Codes (HS Codes)',
    slug: 'decoding-customs-tariff-codes-hs-codes',
    category: 'Customs Information',
    status: 'Published',
    publishDate: '2026-07-19',
    author: 'Admin',
    readTime: '8 minutes',
    shortSummary: 'Master Harmonized System codes to prevent duty calculation errors and speed up border inspection clearance.',
    bodyContent: 'HS codes classify commercial goods for global trade duty assessment.',
    featuredImage: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=800&q=80',
    targetKeywords: 'HS codes, customs tariffs, duty calculation, cross-border commerce',
    seoTitle: 'Understanding Harmonized System (HS) Codes for Shipping',
    seoDescription: 'Learn how proper HS tariff classification prevents customs holds and unexpected tax bills.',
  },
  {
    id: 'post-5',
    title: 'New Carrier API Integrations in ShipTrack v2.4',
    slug: 'new-carrier-api-integrations-in-shiptrack-v2-4',
    category: 'Tracking Updates',
    status: 'Published',
    publishDate: '2026-07-10',
    author: 'Admin',
    readTime: '3 minutes',
    shortSummary: 'We have added sub-second webhook notifications for regional European and Asian postal services.',
    bodyContent: 'ShipTrack v2.4 introduces direct API feeds for over 25 new regional postal carriers.',
    featuredImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    targetKeywords: 'carrier API, shipment webhooks, tracking updates',
    seoTitle: 'ShipTrack v2.4 Product Release: Expanded Carrier APIs',
    seoDescription: 'Explore the newest carrier integrations supporting instant tracking webhooks globally.',
  },
  {
    id: 'post-6',
    title: 'Preparing Your Business for Peak Season Logistics',
    slug: 'preparing-your-business-for-peak-season-logistics',
    category: 'Logistics News',
    status: 'Draft',
    publishDate: '2026-08-02',
    author: 'Admin',
    readTime: '7 minutes',
    shortSummary: 'Key operational strategies for e-commerce retailers managing holiday order volume spikes.',
    bodyContent: 'Peak shopping seasons strain fulfillment centers and carrier distribution hubs.',
    featuredImage: '',
    targetKeywords: 'peak season shipping, ecommerce logistics, holiday delivery',
    seoTitle: 'E-commerce Peak Season Logistics Checklist',
    seoDescription: 'Prepare your warehouse and fulfillment workflows for Q4 surge order volumes.',
  },
  {
    id: 'post-7',
    title: 'How Last-Mile Delivery Optimization Works',
    slug: 'how-last-mile-delivery-optimization-works',
    category: 'Shipping Tips',
    status: 'Published',
    publishDate: '2026-06-25',
    author: 'Admin',
    readTime: '5 minutes',
    shortSummary: 'Exploring dynamic route planning and doorstep delivery verification technologies.',
    bodyContent: 'The last mile represents up to 53% of total freight movement costs.',
    featuredImage: '',
    targetKeywords: 'last mile delivery, route optimization, courier dispatch',
    seoTitle: 'Guide to Last-Mile Delivery Efficiency',
    seoDescription: 'Discover how modern dispatch algorithms reduce transit times and fuel consumption.',
  },
  {
    id: 'post-8',
    title: 'Duty-Free Thresholds and Import Tax Rules Explained',
    slug: 'duty-free-thresholds-and-import-tax-rules-explained',
    category: 'Customs Information',
    status: 'Draft',
    publishDate: '2026-08-01',
    author: 'Admin',
    readTime: '6 minutes',
    shortSummary: 'De minimis limits across major trade zones including the US, EU, and UK.',
    bodyContent: 'Understanding tax exemption limits prevents recipient unexpected COD charges.',
    featuredImage: '',
    targetKeywords: 'de minimis, import tax, duty free threshold, customs duty',
    seoTitle: 'Global Duty-Free Import Thresholds Guide',
    seoDescription: 'Compare de minimis values and taxation formulas across top international destinations.',
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'act-1',
    message: 'Admin login — admin@shiptrack.com',
    timestamp: 'Today at 06:12 AM',
    type: 'login',
  },
  {
    id: 'act-2',
    message: 'New post published: How to Track International Shipments',
    timestamp: 'Today at 05:30 AM',
    type: 'publish',
  },
  {
    id: 'act-3',
    message: 'Category added: Customs Information',
    timestamp: 'Yesterday at 02:15 PM',
    type: 'category',
  },
  {
    id: 'act-4',
    message: 'Draft saved: Understanding Express Air Freight',
    timestamp: 'Yesterday at 11:20 AM',
    type: 'draft',
  },
];

export const INITIAL_SEO_CONFIG: SeoConfig = {
  sitemapUrl: 'https://shiptrack.com/sitemap.xml',
  sitemapLastGenerated: '2026-08-08 05:30 UTC',
  robotsTxt: `User-agent: *
Allow: /
Allow: /blog/
Allow: /tracking/
Disallow: /admin/
Disallow: /api/private/
Sitemap: https://shiptrack.com/sitemap.xml`,
  robotsLastUpdated: '2026-08-05 12:00 UTC',
  metaTitleSuffix: '| ShipTrack Parcel Intelligence',
  canonicalEnabled: true,
  globalMetaDescription: 'ShipTrack CMS powers official blog updates, logistics guides, customs advice, and package tracking knowledge for international shippers.',
};
